In [22]:

%%writefile np_test1.txt
0 1 2 3 5
8 6 4 9 3

Overwriting np_test1.txt


In [23]:
import numpy as np

In [24]:
l_1 =[]
with open("np_test1.txt") as f:
    for line in f.readlines():
        s = line.split()
        cur_list = [float(x) for x in s]
        l_1.append(cur_list)
arr_1 = np.array(l_1)
arr_1

array([[0., 1., 2., 3., 5.],
       [8., 6., 4., 9., 3.]])

In [25]:
arr_2 = np.loadtxt("np_test1.txt")
arr_2

array([[0., 1., 2., 3., 5.],
       [8., 6., 4., 9., 3.]])

In [26]:
%%writefile np_test2.txt
0, 1, 2, 3, 5
8, 6, 4, 9, 3

Overwriting np_test2.txt


In [27]:
arr_2 = np.loadtxt("np_test2.txt", delimiter=",")
arr_2

array([[0., 1., 2., 3., 5.],
       [8., 6., 4., 9., 3.]])

In [30]:
%%writefile np_test3.txt
going well
0, 1, 2, 3, 5
8, 6, 4, 9, 3

Overwriting np_test3.txt


In [32]:
arr_3 = np.loadtxt("np_test3.txt", delimiter=",", skiprows = 1)
arr_3

array([[0., 1., 2., 3., 5.],
       [8., 6., 4., 9., 3.]])