In [1]:
import numpy as np

In [7]:
arr_3 = np.array([[1,2,3,4,5],[1,3,5,7,8]])
arr_3

array([[1, 2, 3, 4, 5],
       [1, 3, 5, 7, 8]])

In [8]:
arr_3.shape

(2, 5)

In [9]:
arr_3 = arr_3[:,np.newaxis]
arr_3.shape

(2, 1, 5)

In [10]:
arr_3 = arr_3.transpose()
arr_3

array([[[1, 1]],

       [[2, 3]],

       [[3, 5]],

       [[4, 7]],

       [[5, 8]]])

In [11]:
arr_3.T

array([[[1, 2, 3, 4, 5]],

       [[1, 3, 5, 7, 8]]])

In [12]:
arr_4 = np.array([[1,2,3,4,5],[1,3,5,7,8]])
arr_4

array([[1, 2, 3, 4, 5],
       [1, 3, 5, 7, 8]])

In [13]:
arr_5 = np.array([[2,4,2,4,6],[1,3,5,7,8]])
arr_5

array([[2, 4, 2, 4, 6],
       [1, 3, 5, 7, 8]])

In [16]:
arr_6 = np.concatenate((arr_4,arr_5))
arr_6

array([[1, 2, 3, 4, 5],
       [1, 3, 5, 7, 8],
       [2, 4, 2, 4, 6],
       [1, 3, 5, 7, 8]])

In [17]:
np.vstack((arr_4,arr_5))

array([[1, 2, 3, 4, 5],
       [1, 3, 5, 7, 8],
       [2, 4, 2, 4, 6],
       [1, 3, 5, 7, 8]])

In [19]:
np.hstack((arr_4,arr_5))

array([[1, 2, 3, 4, 5, 2, 4, 2, 4, 6],
       [1, 3, 5, 7, 8, 1, 3, 5, 7, 8]])

In [20]:
arr_6.flatten()

array([1, 2, 3, 4, 5, 1, 3, 5, 7, 8, 2, 4, 2, 4, 6, 1, 3, 5, 7, 8])

In [21]:
arr_6

array([[1, 2, 3, 4, 5],
       [1, 3, 5, 7, 8],
       [2, 4, 2, 4, 6],
       [1, 3, 5, 7, 8]])

In [22]:
arr_6.ravel()

array([1, 2, 3, 4, 5, 1, 3, 5, 7, 8, 2, 4, 2, 4, 6, 1, 3, 5, 7, 8])