In [5]:
import numpy as np
arr_1 = np.array([[1,2,3],[3,4,5]])
arr_1

array([[1, 2, 3],
       [3, 4, 5]])

In [6]:
np.sum(arr_1)

18

In [7]:
np.sum(arr_1,axis=1)

array([ 6, 12])

In [9]:
arr_1.prod()

360

In [10]:
arr_1.prod(axis=1)

array([ 6, 60])

In [13]:
arr_1.prod(axis=0)

array([ 3,  8, 15])

In [15]:
arr_1.min(axis=0)

array([1, 2, 3])

In [16]:
arr_1.argmin()

0

In [17]:
arr_1.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [18]:
arr_1.argmax()

5

In [19]:
arr_1.mean()

3.0

In [21]:
arr_1.mean(axis=0)

array([2., 3., 4.])

In [22]:
arr_1.std()

1.2909944487358056

In [23]:
arr_1.std(axis=1)

array([0.81649658, 0.81649658])

In [25]:
arr_1.var(axis=1)

array([0.66666667, 0.66666667])

In [26]:
arr_1

array([[1, 2, 3],
       [3, 4, 5]])

In [29]:
arr_1.clip(2,4) 

array([[2, 2, 3],
       [3, 4, 4]])

In [32]:
arr_2 = np.array([4.23,5.43,9.94])
arr_2.round()

array([ 4.,  5., 10.])

In [36]:
arr_2 = np.array([4.23,5.433,9.94])
arr_2.round(decimals=3)

array([4.23 , 5.433, 9.94 ])