In [12]:
import numpy as np

In [17]:
m_1 = np.array([[1,2,3],
                [4,5,6],
                [3,6,8]])
m_1

array([[1, 2, 3],
       [4, 5, 6],
       [3, 6, 8]])

In [18]:
m_1.shape

(3, 3)

In [19]:
m_1.size

9

In [20]:
m_1[1,2]= 16
m_1

array([[ 1,  2,  3],
       [ 4,  5, 16],
       [ 3,  6,  8]])

In [21]:
m_1[:,1]

array([2, 5, 6])

In [22]:
m_1[0,:]

array([1, 2, 3])

In [23]:
m_2 = m_1
m_2

array([[ 1,  2,  3],
       [ 4,  5, 16],
       [ 3,  6,  8]])

In [24]:
m_2[1,2]=600
m_2

array([[  1,   2,   3],
       [  4,   5, 600],
       [  3,   6,   8]])

In [25]:
m_1

array([[  1,   2,   3],
       [  4,   5, 600],
       [  3,   6,   8]])

In [26]:
m_1 = np.array([[1,2,3],
                [4,5,6],
                [3,6,8]])
m_3 = m_1.copy()
m_3

array([[1, 2, 3],
       [4, 5, 6],
       [3, 6, 8]])

In [27]:
m_1

array([[1, 2, 3],
       [4, 5, 6],
       [3, 6, 8]])

In [31]:
m_4 = np.arange(0,100,20)
m_4

array([ 0, 20, 40, 60, 80])

In [37]:
m_5 = np.random.rand(10,4)
m_5

array([[0.65558311, 0.919952  , 0.80075766, 0.83366377],
       [0.07039168, 0.77837531, 0.2060411 , 0.40636997],
       [0.74994874, 0.85952674, 0.14775425, 0.62004624],
       [0.67558583, 0.03888351, 0.01743223, 0.87012829],
       [0.96896865, 0.98579794, 0.76070439, 0.67951517],
       [0.57639404, 0.21528041, 0.97720594, 0.83212249],
       [0.2424736 , 0.09336967, 0.413326  , 0.84542763],
       [0.73109697, 0.60320959, 0.94070392, 0.29949655],
       [0.6231365 , 0.50548222, 0.24417861, 0.8963055 ],
       [0.55019101, 0.7602819 , 0.67016942, 0.13813342]])

In [43]:
arr_1 = np.array([1,2,3], dtype = np.float32)
arr_1

array([1., 2., 3.], dtype=float32)

In [47]:
arr_1.nbytes

12

In [52]:
arr_1

array([1., 2., 3.], dtype=float32)

In [53]:
arr_4 = np.asarray(arr_1, dtype = np.float32)

In [54]:
arr_4

array([1., 2., 3.], dtype=float32)