In [4]:
import numpy as np

In [12]:
np.random.randint(35,size = (5,5))

array([[33,  4, 13, 17,  8],
       [28, 24, 33,  7, 16],
       [31, 16, 23,  7, 14],
       [ 4, 11, 13,  5, 33],
       [ 1, 23, 32,  1, 25]])

In [13]:
np.random.randint(0,30,7)

array([ 7,  5, 21,  3,  7, 17,  7])

In [15]:
arr_1 = np.arange(100)
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
np.random.shuffle(arr_1)

arr_1

array([86, 80, 16, 62, 18, 24, 75, 49, 61, 19, 34, 39, 91, 54, 79, 56, 65,
       66, 53, 58, 67, 30, 78, 73, 85,  2, 45, 96,  3, 77, 23,  6, 17, 26,
       28,  7,  9, 82, 87, 47, 14, 72, 98, 32, 93, 90, 83, 94, 20, 74,  4,
       48, 42, 52, 99, 70, 43, 95, 31, 50, 40, 27, 41, 63,  5, 29, 25, 13,
       64, 71, 57,  0, 51, 76, 69, 84, 35, 97, 37, 55, 11, 60, 81, 46, 89,
       21,  8, 12, 92, 10, 44, 15, 68, 59, 22, 33, 38, 36,  1, 88])

In [19]:
arr_2 = np.sort(arr_1)
arr_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [33]:
np.random.seed(2)

In [34]:
np.random.rand(4,4)

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239],
       [0.4203678 , 0.33033482, 0.20464863, 0.61927097],
       [0.29965467, 0.26682728, 0.62113383, 0.52914209],
       [0.13457995, 0.51357812, 0.18443987, 0.78533515]])