In [1]:
import numpy as np

In [3]:
arr_1 = np.array([[1,2,3,],[4,6,3]])
arr_1

array([[1, 2, 3],
       [4, 6, 3]])

In [8]:
arr_2 = np.sort(arr_1)
arr_2

array([[1, 2, 3],
       [3, 4, 6]])

In [5]:
arr_1

array([[1, 2, 3],
       [4, 6, 3]])

In [9]:
np.argsort(arr_1)

array([[0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [15]:
arr_3 = np.arange(0,10,2)
arr_3

array([0, 2, 4, 6, 8])