In [1]:
## TASK: To create a 4x4 size array of all 1 and border of zeroes ##

In [3]:
import numpy as np

In [6]:
arr_1 = np.ones((4,4))
arr_1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
arr_1 = np.pad(arr_1,pad_width=1, mode="constant", constant_values = 0)
arr_1

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
arr_1 = np.pad(arr_1,pad_width=2, mode="constant", constant_values = 0)
arr_1

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])